proxy:
  port: "80"
  host: "0.0.0.0"
  # url prefix for proxy
  target: "https://github.com/"  
  # log files path configuration 
  log: 
    err_log: "./log/error.log" 
    info_log: "./log/info.log"
  db: 
    port: "6379"
    # name used to resolve address of the instance within the network
    name: "cache" 

reverse_proxy:
  expose: "8080"
